years = ["2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019"]
agencyabb = ["DHS","DOC","DOD","DOJ","GSA","HHS","SEC","TREAS","USDA","VA"]

agencycode = ["070","013","097","015","047","075","050","020","012","036"]

agencytoptier = ["63","15","126","17","40","68","47","22","14","37"]

# toptier_agency_id	toptier_code	abbreviation	name
# 63			70		DHS		Department of Homeland Security
# 15			13		DOC		Department of Commerce
# 126			97		DOD		Department of Defense
# 17			15		DOJ		Department of Justice
# 40			47		GSA		General Services Administration
# 68			75		HHS		Department of Health and Human Services
# 47			50		SEC		Securities and Exchange Commission
# 22			20		TREAS	Department of the Treasury
# 14			12		USDA	Department of Agriculture
# 37			36		VA		Department of Veterans Affairs


agencyname = [
                "Department of Homeland Security",
                "Department of Commerce",
                "Department of Defense",
                "Department of Justice",
                "General Services Administration",
                "Department of Health and Human Services",                
                "Securities and Exchange Commission",
                "Department of the Treasury",
                "Department of Veterans Affairs",
                "Department of Agriculture",
                ]


selectedcolumns =[
			'action_date',
			'awarding_agency_code',
			'awarding_agency_name',
			'awarding_sub_agency_code',
			'awarding_sub_agency_name',
			'period_of_performance_start_date',
			'period_of_performance_current_end_date',
			'naics_code',
			'naics_description',
			'base_and_all_options_value',
			'type_of_contract_pricing_code',
			'type_of_contract_pricing',
			'award_description',
			'contracting_officers_determination_of_business_size',
			'contracting_officers_determination_of_business_size_code',
			'primary_place_of_performance_country_code',
			'primary_place_of_performance_country_name',
			'primary_place_of_performance_city_name',
			'primary_place_of_performance_county_name',
			'primary_place_of_performance_state_code',
			'primary_place_of_performance_state_name',
			'primary_place_of_performance_zip_4',
			'primary_place_of_performance_congressional_district',
			'recipient_parent_duns',
			'recipient_parent_name',
			'recipient_country_code',
			'recipient_country_name',
			'recipient_address_line_1',
			'recipient_address_line_2',
			'recipient_city_name',
			'recipient_county_name',
			'recipient_state_code',
			'recipient_state_name',
			'recipient_zip_4_code',
			'recipient_congressional_district',
			'recipient_phone_number',
			'extent_competed_code',
			'extent_competed',
			'solicitation_procedures_code',
			'solicitation_procedures',
			'purchase_card_as_payment_method_code',
			'purchase_card_as_payment_method',
			'multi_year_contract_code',
			'multi_year_contract',
			'product_or_service_code',
			'product_or_service_code_description',
            'foreign_funding',
            'foreign_funding_description',
            'sam_exception',
            'sam_exception_description',
            'total_dollars_obligated',
            'action_date_fiscal_year',
            'ordering_period_end_date',
            'solicitation_date',
            'recipient_duns',
            'recipient_name',
            'award_or_idv_flag',
            'award_type_code',
            'award_type',
            'idv_type_code',
            'idv_type',
            'multiple_or_single_award_idv_code',
            'multiple_or_single_award_idv'
            ]

filtercolumns1 =[
			'action_date',
			'awarding_agency_code',
			'awarding_agency_name',
			'period_of_performance_start_date',
			'period_of_performance_current_end_date',
			'naics_code',
			'naics_description',
			'base_and_all_options_value',
			'type_of_contract_pricing_code',
			'type_of_contract_pricing',
			'award_description',
			'contracting_officers_determination_of_business_size',
			'contracting_officers_determination_of_business_size_code',
			'primary_place_of_performance_country_code',
			'primary_place_of_performance_country_name',
			'primary_place_of_performance_city_name',
			'primary_place_of_performance_county_name',
			'primary_place_of_performance_state_code',
			'primary_place_of_performance_state_name',
			'primary_place_of_performance_zip_4',
            'recipient_duns',
            'recipient_name',
   			'recipient_parent_duns',
			'recipient_parent_name',
			'recipient_country_code',
			'recipient_country_name',
			'recipient_city_name',
            'recipient_state_code',
			'recipient_state_name',
			'solicitation_procedures_code',
			'solicitation_procedures',
			'product_or_service_code',
			'product_or_service_code_description',
            'total_dollars_obligated',
            'action_date_fiscal_year',
            'ordering_period_end_date',
            'solicitation_date',
            'award_or_idv_flag',
            'award_type_code',
            'award_type'
            ]

forplot1 = [
            'contract_award_unique_key',
            'awarding_agency_code',        
            'action_date_fiscal_year',
            'total_dollars_obligated',
            'recipient_duns',
            'recipient_name',
            'recipient_state_code',
			'naics_code',
            'product_or_service_code',
            'base_and_all_options_value',
            'type_of_contract_pricing_code',
            'extent_competed_code',
            'primary_place_of_performance_country_code'
        ]


forplotdtype = {
            'contract_award_unique_key':str,
            'awarding_agency_code':str,        
            'action_date_fiscal_year':str,
            'total_dollars_obligated':float,
            'recipient_duns':str,
            'recipient_name':str,
            'recipient_state_code':str,
			'naics_code':str,
            'product_or_service_code':str,
            'base_and_all_options_value':float,
            'type_of_contract_pricing_code':str,
            'extent_competed_code':str,
            'primary_place_of_performance_country_code':str
            }


selected_naics = ['541511','541512','541513','541519']

forcount1 = [
            'contract_award_unique_key',        
            'awarding_agency_code',        
            'action_date_fiscal_year',
            'base_and_all_options_value',
            'recipient_duns',
            'recipient_name'
        ]

forcountdtype = {
               'contract_award_unique_key':str,
               'awarding_agency_code':str,        
               'action_date_fiscal_year':str,
               'base_and_all_options_value':float,
               'recipient_duns':str,
               'recipient_name':str
               }       
            
forana1 = [
            'contract_award_unique_key',
            'contract_transaction_unique_key',
            'awarding_agency_code',        
            'award_id_piid',
            'modification_number',
            'transaction_number',
            'parent_award_agency_id',
            'parent_award_agency_name',
            'parent_award_id_piid',
            'parent_award_modification_number',
            'federal_action_obligation',
            'total_dollars_obligated',
            'recipient_doing_business_as_name',
            'recipient_parent_duns',
            'recipient_parent_name',
            'action_type_code',
            'action_type',
            'solicitation_identifier',
            'number_of_actions',
            'recipient_duns',
            'recipient_name',
            'recipient_state_code',
            'base_and_all_options_value',
            'type_of_contract_pricing_code',
            'primary_place_of_performance_country_code',
            'federal_action_obligation',
            'base_and_exercised_options_value',
            'action_date',
            'action_date_fiscal_year',
            'period_of_performance_start_date',
            'period_of_performance_current_end_date',
            'funding_office_code',
            'funding_office_name',
            'naics_code',
			'naics_description',
			'multi_year_contract',
			'product_or_service_code',
			'product_or_service_code_description',
			'base_and_all_options_value',
			'type_of_contract_pricing_code',
			'type_of_contract_pricing',
			'award_description',
			'contracting_officers_determination_of_business_size',
			'contracting_officers_determination_of_business_size_code',
            'extent_competed_code',
            'extent_competed',
            'award_type_code',
            'award_type',
			'solicitation_procedures_code',
			'solicitation_procedures',
            'purchase_card_as_payment_method',
            'awarding_agency_code',
			'awarding_agency_name',
			'awarding_sub_agency_code',
			'awarding_sub_agency_name',
            'period_of_performance_potential_end_date',
            'ordering_period_end_date',
        	'primary_place_of_performance_city_name',
			'primary_place_of_performance_state_code',
			'primary_place_of_performance_state_name',
			'recipient_city_name',
            'recipient_state_code',
			'recipient_state_name'
            ]

foranadtype = {
            'action_date_fiscal_year':str,
            'contract_award_unique_key':str,
            'contract_transaction_unique_key':str,
            'awarding_agency_code':str,        
            'award_id_piid':str,
            'modification_number':str,
            'transaction_number':str,
            'parent_award_agency_id':str,
            'parent_award_agency_name':str,
            'parent_award_id_piid':str,
            'parent_award_modification_number':str,
            'federal_action_obligation':float,
            'total_dollars_obligated':float,
            'recipient_doing_business_as_name':str,
            'recipient_parent_duns':str,
            'recipient_parent_name':str,
            'action_type_code':str,
            'action_type':str,
            'solicitation_identifier':str,
            'number_of_actions':str,
            'recipient_duns':str,
            'recipient_name':str,
            'recipient_state_code':str,
            'base_and_all_options_value':float,
            'type_of_contract_pricing_code':str,
            'primary_place_of_performance_country_code':str,
            'base_and_exercised_options_value':float,
            'action_date':str,
            'action_date_fiscal_year':str,
            'period_of_performance_start_date':str,
            'period_of_performance_current_end_date':str,
            'funding_office_code':str,
            'funding_office_name':str,
            'naics_code':str,
			'naics_description':str,
			'multi_year_contract':str,
			'product_or_service_code':str,
			'product_or_service_code_description':str,
			'base_and_all_options_value':float,
			'type_of_contract_pricing_code':str,
			'type_of_contract_pricing':str,
			'award_description':str,
			'contracting_officers_determination_of_business_size':str,
			'contracting_officers_determination_of_business_size_code':str,
            'extent_competed_code':str,
            'extent_competed':str,
            'award_type_code':str,
            'award_type':str,
			'solicitation_procedures_code':str,
			'solicitation_procedures':str,
           	'purchase_card_as_payment_method':str,
            'awarding_agency_code':str,
			'awarding_agency_name':str,
			'awarding_sub_agency_code':str,
			'awarding_sub_agency_name':str,
            'period_of_performance_potential_end_date':str,
            'ordering_period_end_date':str,
        	'primary_place_of_performance_city_name':str,
			'primary_place_of_performance_state_code':str,
			'primary_place_of_performance_state_name':str,
			'recipient_city_name':str,
            'recipient_state_code':str,
			'recipient_state_name':str
            }

parse_dates = ['action_date', 'period_of_performance_start_date', 'period_of_performance_current_end_date']
#from datetime import datetime
#mydateparser = lambda x: pd.datetime.strptime(x, "%Y %m %d %H:%M:%S")
